name: Run Jest Test and SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci
          npm install --save-dev jest @babel/preset-env babel-jest

      - name: Install client dependencies
        working-directory: client
        run: npm ci

      - name: Run Jest server tests
        run: npm run test:backend -- --silent
        env:
          CI: true

      - name: Run Jest client tests
        run: npm run test:frontend -- --silent
        env:
          CI: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install SonarQube Scanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: sqa_0f5269ea22e3abcb15bca74502059fc3e65d3203
        run: |
          sonar-scanner \
            -Dsonar.projectKey=econ \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://132.226.117.124 \
            -Dsonar.token=sqa_0f5269ea22e3abcb15bca74502059fc3e65d3203 \
            -Dsonar.javascript.lcov.reportPaths=coverage/**/lcov.info